# Generated by Django 5.0.6 on 2024-06-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='titlr',
            new_name='title',
        ),
    ]
